Repository kakao-tech-campus-2nd-step3/Team10_FE, pull requests merged in 2024-10, with the labels that each got.

#19 Feature/footer UI #17
  src/components/layouts/Footer.tsx
  src/components/layouts/MainLayout.tsx
  src/constants/size.ts
  src/index.tsx
  src/providers.tsx
  src/theme/index.ts
  tsconfig.paths.json
Labels: 💎 기능 개발, 🎨 디자인

#28 Feature/store top component #27
  src/assets/Image/Store/Store1.png
  src/assets/Image/Store/Store2.png
  src/assets/Image/Store/Store3.png
  src/components/features/StorePage/HeaderBanner.tsx
  src/components/features/StorePage/Review.tsx
Labels: 💎 기능 개발

#39 Feature/list view #30
  src/components/ItemView/ListView.tsx
  src/components/ItemView/type.ts
  src/components/common/Card.tsx
  src/mocks/mockItem.ts
  src/types/index.ts
  tsconfig.paths.json
Labels: 💎 기능 개발

#41 Feature/product card #29
  src/components/ItemView/GridView.tsx
  src/components/ItemView/ListView.tsx
  src/components/ItemView/type.ts
  src/components/features/StorePage/ProductCard.tsx
  src/mocks/mockItem.ts
  src/mocks/mockItem/mockFarms.ts
  src/mocks/mockItem/mockMainProducts.ts
  src/mocks/mockItem/mockProducts.ts
  src/types/index.ts
  tsconfig.paths.json
Labels: 💎 기능 개발, 🎨 디자인

#35 개발 4주차 최종코드
  public/assets/image/default-image.svg
  src/assets/Image/Store/Store1.png
  src/assets/Image/Store/Store2.png
  src/assets/Image/Store/Store3.png
  src/components/ItemView/GridView.tsx
  src/components/ItemView/ListView.tsx
  src/components/ItemView/type.ts
  src/components/common/Avatar.tsx
  src/components/common/Card.tsx
  src/components/common/Image.tsx
  src/components/common/ImageCard.tsx
  src/components/features/IntroductionPage/Introduction.tsx
  src/components/features/SchedulePage/BestScheduleCard.tsx
  src/components/features/SchedulePage/BestScheduleSection.tsx
  src/components/features/StorePage/HeaderBanner.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/features/StorePage/Review.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/constants/size.ts
  src/mocks/mockItem/mockBestSchedule.ts
  src/mocks/mockItem/mockFarms.ts
  src/mocks/mockItem/mockMainProducts.ts
  src/mocks/mockItem/mockProducts.ts
  src/mocks/mockItem/mockSchedule.ts
  src/pages/Home/index.tsx
  src/types/index.ts
  tsconfig.paths.json
Labels: 💎 기능 개발, 🎨 디자인, 🔨 리팩토링

#51 개발 4.5 주차 최종코드
  public/assets/image/default-image.svg
  src/assets/Image/Store/Store1.png
  src/assets/Image/Store/Store2.png
  src/assets/Image/Store/Store3.png
  src/components/ItemView/GridView.tsx
  src/components/ItemView/ListView.tsx
  src/components/ItemView/type.ts
  src/components/common/Avatar.tsx
  src/components/common/Card.tsx
  src/components/common/Image.tsx
  src/components/common/ImageCard.tsx
  src/components/features/IntroductionPage/Introduction.tsx
  src/components/features/SchedulePage/BestScheduleCard.tsx
  src/components/features/SchedulePage/BestScheduleSection.tsx
  src/components/features/StorePage/HeaderBanner.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/features/StorePage/Review.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/constants/size.ts
  src/mocks/mockItem/mockBestSchedule.ts
  src/mocks/mockItem/mockFarms.ts
  src/mocks/mockItem/mockMainProducts.ts
  src/mocks/mockItem/mockProducts.ts
  src/mocks/mockItem/mockSchedule.ts
  src/pages/Home/index.tsx
  src/types/index.ts
  tsconfig.paths.json
Labels: 💎 기능 개발, 🎨 디자인

#50 Feature/StoreDetailPage #43
  package-lock.json
  package.json
  src/assets/Image/Farm/Farm1.png
  src/assets/Image/Farm/Farm2.png
  src/assets/Image/Farm/Farm3.png
  src/assets/Image/Farm/Farm4.png
  src/assets/Image/Farm/Farm5.png
  src/assets/Image/Farm/Farm6.png
  src/assets/Image/Store/Store4.png
  src/assets/Image/Store/Store5.png
  src/assets/Image/Store/Store6.png
  src/assets/Image/Store/Store7.png
  src/assets/Image/Store/Store8.png
  src/components/features/BuyerMyPage/OrderList.tsx
  src/components/features/BuyerMyPage/Pay.tsx
  src/components/features/BuyerMyPage/ReviewList.tsx
  src/components/features/FarmDetailPage/Direciton.tsx
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/Reviews.tsx
  src/components/features/SellerMyPage/CompletedDeliveryList.tsx
  src/components/features/SellerMyPage/DeliveryOrderList.tsx
  src/components/features/SellerMyPage/PickupOrderList.tsx
  src/components/features/SellerMyPage/ReturnOrderList.tsx
  src/components/features/StoreDetailPage/Direction.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/features/StoreDetailPage/ProductDescription.tsx
  src/components/features/StoreDetailPage/ReviewList.tsx
  src/components/features/StoreDetailPage/Reviews.tsx
  src/pages/BuyerMyPage/index.tsx
  src/pages/FarmDetailPage/index.tsx
  src/pages/SellerMyPage/index.tsx
  src/pages/StoreDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 💎 기능 개발, 🎨 디자인
