Repository kakao-tech-campus-2nd-step3/Team10_FE, pull requests merged in 2024-11, with the labels that each got.

#54 Feature/modal #53
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/modal/BasicModal.tsx
  src/components/features/MyPage/ContactModal.tsx
  src/components/features/MyPage/OrderProcessModal.tsx
Labels: 💎 기능 개발, 🎨 디자인

#57 Weekly7
  .eslintrc.cjs
  package-lock.json
  package.json
  src/assets/Image/Farm/Farm1.png
  src/assets/Image/Farm/Farm3.png
  src/assets/Image/Farm/Farm4.png
  src/assets/Image/Farm/Farm5.png
  src/assets/Image/Farm/Farm6.png
  src/assets/Image/Store/Store4.png
  src/assets/Image/Store/Store5.png
  src/assets/Image/Store/Store6.png
  src/assets/Image/Store/Store7.png
  src/assets/Image/Store/Store8.png
  src/components/common/modal/BasicModal.tsx
  src/components/features/BuyerMyPage/OrderList.tsx
  src/components/features/BuyerMyPage/Pay.tsx
  src/components/features/BuyerMyPage/ReviewList.tsx
  src/components/features/FarmDetailPage/Direciton.tsx
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/Reviews.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/ContactModal.tsx
  src/components/features/MyPage/OrderProcessModal.tsx
  src/components/features/SellerMyPage/CompletedDeliveryList.tsx
  src/components/features/SellerMyPage/DeliveryOrderList.tsx
  src/components/features/SellerMyPage/PickupOrderList.tsx
  src/components/features/SellerMyPage/ReturnOrderList.tsx
  src/components/features/StoreDetailPage/Direction.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/features/StoreDetailPage/ProductDescription.tsx
  src/components/features/StoreDetailPage/ReviewList.tsx
  src/components/features/StoreDetailPage/Reviews.tsx
  src/pages/BuyerMyPage/index.tsx
  src/pages/FarmDetailPage/index.tsx
  src/pages/SellerMyPage/index.tsx
  src/pages/StoreDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 💎 기능 개발, 🎨 디자인

#58 Develop
  .eslintrc.cjs
  package-lock.json
  package.json
  src/assets/Image/Farm/Farm1.png
  src/assets/Image/Farm/Farm3.png
  src/assets/Image/Farm/Farm4.png
  src/assets/Image/Farm/Farm5.png
  src/assets/Image/Farm/Farm6.png
  src/assets/Image/Store/Store4.png
  src/assets/Image/Store/Store5.png
  src/assets/Image/Store/Store6.png
  src/assets/Image/Store/Store7.png
  src/assets/Image/Store/Store8.png
  src/components/common/modal/BasicModal.tsx
  src/components/features/BuyerMyPage/OrderList.tsx
  src/components/features/BuyerMyPage/Pay.tsx
  src/components/features/BuyerMyPage/ReviewList.tsx
  src/components/features/FarmDetailPage/Direciton.tsx
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/Reviews.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/ContactModal.tsx
  src/components/features/MyPage/OrderProcessModal.tsx
  src/components/features/SellerMyPage/CompletedDeliveryList.tsx
  src/components/features/SellerMyPage/DeliveryOrderList.tsx
  src/components/features/SellerMyPage/PickupOrderList.tsx
  src/components/features/SellerMyPage/ReturnOrderList.tsx
  src/components/features/StoreDetailPage/Direction.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/features/StoreDetailPage/ProductDescription.tsx
  src/components/features/StoreDetailPage/ReviewList.tsx
  src/components/features/StoreDetailPage/Reviews.tsx
  src/pages/BuyerMyPage/index.tsx
  src/pages/FarmDetailPage/index.tsx
  src/pages/SellerMyPage/index.tsx
  src/pages/StoreDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 💎 기능 개발, 🎨 디자인

#59 개발 7주차 (9주차) 코드 리뷰
  .eslintrc.cjs
  package-lock.json
  package.json
  src/assets/Image/Farm/Farm1.png
  src/assets/Image/Farm/Farm3.png
  src/assets/Image/Farm/Farm4.png
  src/assets/Image/Farm/Farm5.png
  src/assets/Image/Farm/Farm6.png
  src/assets/Image/Store/Store4.png
  src/assets/Image/Store/Store5.png
  src/assets/Image/Store/Store6.png
  src/assets/Image/Store/Store7.png
  src/assets/Image/Store/Store8.png
  src/components/common/modal/BasicModal.tsx
  src/components/features/BuyerMyPage/OrderList.tsx
  src/components/features/BuyerMyPage/Pay.tsx
  src/components/features/BuyerMyPage/ReviewList.tsx
  src/components/features/FarmDetailPage/Direciton.tsx
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/Reviews.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/ContactModal.tsx
  src/components/features/MyPage/OrderProcessModal.tsx
  src/components/features/SellerMyPage/CompletedDeliveryList.tsx
  src/components/features/SellerMyPage/DeliveryOrderList.tsx
  src/components/features/SellerMyPage/PickupOrderList.tsx
  src/components/features/SellerMyPage/ReturnOrderList.tsx
  src/components/features/StoreDetailPage/Direction.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/features/StoreDetailPage/ProductDescription.tsx
  src/components/features/StoreDetailPage/ReviewList.tsx
  src/components/features/StoreDetailPage/Reviews.tsx
  src/pages/BuyerMyPage/index.tsx
  src/pages/FarmDetailPage/index.tsx
  src/pages/SellerMyPage/index.tsx
  src/pages/StoreDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 💎 기능 개발, 🎨 디자인

#64 Feature/Add env on BuildTest #63
  .github/workflows/pr_precheck.yml
Labels: ⚙️ 세팅

#62 Feature/map #61
  package-lock.json
  package.json
  public/index.html
  src/components/common/KaKaoMap/ResetMapBounds.tsx
  src/components/common/KaKaoMap/index.tsx
  src/components/common/KaKaoMap/type.ts
  tsconfig.json
Labels: 💎 기능 개발

#66 Feature/write review component #65
  package-lock.json
  package.json
  src/components/common/StarRating.tsx
  src/components/features/MyPage/WriteReviewComponent.tsx
  src/components/features/SellerPage/AddFarm/BasicInfo.tsx
  src/components/features/SellerPage/AddFarm/DetailInfo.tsx
  src/components/features/SellerPage/AddFarm/PriceInfo.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/AddProduct/BasicInfo.tsx
  src/components/features/SellerPage/AddProduct/DetailInfo.tsx
  src/components/features/SellerPage/AddProduct/PriceInfo.tsx
  src/components/features/SellerPage/AddProduct/index.tsx
  src/components/features/SellerPage/EditFarm/BasicInfo.tsx
  src/components/features/SellerPage/EditFarm/DetailInfo.tsx
  src/components/features/SellerPage/EditFarm/PriceInfo.tsx
  src/components/features/SellerPage/EditFarm/index.tsx
  src/components/features/SellerPage/EditProduct/BasicInfo.tsx
  src/components/features/SellerPage/EditProduct/DetailInfo.tsx
  src/components/features/SellerPage/EditProduct/PriceInfo.tsx
  src/components/features/SellerPage/EditProduct/index.tsx
  src/components/features/SellerPage/SellerCategory.tsx
  src/routes/AppRouter.tsx
  src/types/react-awesome-stars-rating.d.ts
Labels: 💎 기능 개발, 🎨 디자인

#72 Feature/add product modal #71
  src/components/common/modal/BasicModal.tsx
  src/components/features/SellerPage/AddProduct/AddInfo.tsx
  src/components/features/SellerPage/AddProduct/AddProductModal.tsx
  src/components/features/SellerPage/AddProduct/DetailInfo.tsx
Labels: 💎 기능 개발, 🎨 디자인

#99 Feature/cicd #95
  .github/workflows/deploy.yml
  .github/workflows/pr_precheck.yml
  .github/workflows/remove_deploy.yml
Labels: 🌏 배포

#100 CICD를 위한 임시 머지
  .github/workflows/deploy.yml
  .github/workflows/pr_precheck.yml
  .github/workflows/remove_deploy.yml
Labels: 🌏 배포

#101 CICD를 위한 임시 머지
  .github/workflows/deploy.yml
  .github/workflows/pr_precheck.yml
  .github/workflows/remove_deploy.yml
Labels: 🌏 배포

#103 Feature/api #102
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/api/productApi.ts
  src/providers.tsx
Labels: 📪 API

#93 Feature/add farm refactor #92
  src/components/features/MyPage/Category.tsx
  src/components/features/SellerPage/AddFarm/BasicInfo.tsx
Labels: 🔨 리팩토링

#105 Feature/지도검색 #104
  src/components/common/InputAddressWithMap.tsx
  src/utils/mapUtils.ts
Labels: 💎 기능 개발

#107 Feature/상점페이지 #45
  public/assets/image/fresh_veggies.png
  public/assets/image/vegetables.png
  src/components/common/ImageCard.tsx
  src/components/features/StorePage/ProductList/ProductFilter/ProductFilterItemView.tsx
  src/components/features/StorePage/ProductList/ProductFilter/ProductGroupView.tsx
  src/components/features/StorePage/ProductList/ProductFilter/index.tsx
  src/components/features/StorePage/ProductList/ProductFilter/type.ts
  src/components/features/StorePage/ProductList/ProductsView.tsx
  src/components/features/StorePage/ProductList/index.tsx
  src/components/features/StorePage/StoreBanner.tsx
  src/constants/productGroup.ts
  src/constants/size.ts
  src/hooks/useFilters.ts
  src/mocks/mockItem/mockCategory.ts
  src/pages/StorePage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
  src/utils/categoryParser.ts
Labels: 💎 기능 개발

#110 Feature/add product refactor #108
  src/api/farmApi.ts
  src/api/productApi.ts
  src/components/common/AddInfo.tsx
  src/components/common/AddPreview.tsx
  src/components/common/InputAddressWithMap.tsx
  src/components/common/type.ts
  src/components/features/SellerPage/AddFarm/AddFarmModal.tsx
  src/components/features/SellerPage/AddFarm/BasicInfo.tsx
  src/components/features/SellerPage/AddFarm/DetailInfo.tsx
  src/components/features/SellerPage/AddFarm/PriceInfo.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/AddProduct/AddInfo.tsx
  src/components/features/SellerPage/AddProduct/AddProductModal.tsx
  src/components/features/SellerPage/AddProduct/BasicInfo.tsx
  src/components/features/SellerPage/AddProduct/DetailInfo.tsx
  src/components/features/SellerPage/AddProduct/index.tsx
  src/components/features/SellerPage/EditFarm/BasicInfo.tsx
  src/components/features/SellerPage/EditFarm/DetailInfo.tsx
  src/components/features/SellerPage/EditFarm/EditFarmModal.tsx
  src/components/features/SellerPage/EditFarm/EditInfo.tsx
  src/components/features/SellerPage/EditFarm/PriceInfo.tsx
  src/components/features/SellerPage/EditFarm/index.tsx
  src/components/features/SellerPage/EditProduct/BasicInfo.tsx
  src/components/features/SellerPage/EditProduct/DetailInfo.tsx
  src/components/features/SellerPage/EditProduct/EditInfo.tsx
  src/components/features/SellerPage/EditProduct/EditProductModal.tsx
  src/components/features/SellerPage/EditProduct/PriceInfo.tsx
  src/components/features/SellerPage/EditProduct/index.tsx
  src/components/features/SellerPage/SellerCategory.tsx
  src/utils/mapUtils.ts
Labels: 🔨 리팩토링

#111 Feature/농장홈 #46
  src/components/features/SchedulePage/ScheduleCategory.tsx
  src/mocks/mockItem/mockSchedule.ts
  src/pages/SchedulePage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
Labels: 🎨 디자인

#115 Feature/농장홈 #46
  src/assets/Image/Farm/Best1.png
  src/assets/Image/Farm/Best2.png
  src/components/features/SchedulePage/BestScheduleSection.tsx
  src/components/features/SchedulePage/ScheduleCard.tsx
  src/components/features/SchedulePage/ScheduleCategory.tsx
  src/components/features/StorePage/ProductList/ProductFilter/ProductFilterItemView.tsx
  src/components/features/StorePage/ProductList/ProductFilter/ProductGroupView.tsx
  src/components/features/StorePage/ProductList/index.tsx
  src/hooks/useFilters.ts
  src/mocks/mockItem/mockCategory.ts
  src/mocks/mockItem/mockSchedule.ts
  src/pages/SchedulePage/index.tsx
  src/utils/categoryParser.ts
Labels: 💎 기능 개발, 🎨 디자인

#116 Feature/카카오로그인 #106
  public/assets/image/register.png
  public/assets/kakao_login/en/kakao_login_large_narrow.png
  public/assets/kakao_login/en/kakao_login_large_wide.png
  public/assets/kakao_login/en/kakao_login_medium_narrow.png
  public/assets/kakao_login/en/kakao_login_medium_wide.png
  public/assets/kakao_login/ko/kakao_login_large_narrow.png
  public/assets/kakao_login/ko/kakao_login_large_wide.png
  public/assets/kakao_login/ko/kakao_login_medium_narrow.png
  public/assets/kakao_login/ko/kakao_login_medium_wide.png
  src/api/axiosInstance.ts
  src/api/intercepters.ts
  src/assets/logo/Kakao.png
  src/atoms/userAtom.ts
  src/components/common/KaKaoLoginButton.tsx
  src/components/features/RegisterPage/Register.tsx
  src/components/features/RegisterPage/RegisterBackground.tsx
  src/components/layouts/Header.tsx
  src/hooks/useLogin.ts
  src/pages/CallbackPage/index.tsx
  src/pages/EmailLoginPage/index.tsx
  src/pages/EmailRegisterPage/index.tsx
  src/pages/FarmerRegisterPage/index.tsx
  src/pages/RegisterPage/index.tsx
  src/routes/AppRouter.tsx
  src/utils/devLogger.ts
  tsconfig.paths.json
Labels: 💎 기능 개발

#119 Feature/이메일 로그인 #117
  src/api/authApi.ts
  src/api/axiosInstance.ts
  src/components/features/RegisterPage/EmailLogin.tsx
  src/components/features/RegisterPage/EmailRegister.tsx
  src/components/features/RegisterPage/Register.tsx
  src/components/layouts/Header.tsx
  src/hooks/useLogin.ts
  src/routes/AppRouter.tsx
Labels: 💎 기능 개발, 🎨 디자인

#122 feat: ProductItem 구현
  src/components/features/StorePage/ProductItem.tsx
Labels: 💎 기능 개발

#124 Feature/farm detail page refactor #123
  src/components/features/FarmDetailPage/Direciton.tsx
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/ReviewList.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/SellerCategory.tsx
  src/pages/FarmDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 🔨 리팩토링

#126 Feature/router #125
  src/components/features/IntroductionPage/Introduction.tsx
  src/components/features/StorePage/StoreBanner.tsx
  src/components/layouts/Header.tsx
  src/pages/SellerPage/index.tsx
  src/pages/StoreDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 🔨 리팩토링

#128 Feature/farmer register api #127
  src/api/authApi.ts
  src/api/axiosInstance.ts
  src/api/emailApi.ts
  src/api/intercepters.ts
  src/components/features/RegisterPage/Farmer.tsx
  src/hooks/useLogin.ts
Labels: 📪 API

#130 feat: DeliveryInfoModal 구현
  src/components/features/SellerPage/DeliveryInfoModal.tsx
Labels: 💎 기능 개발

#131 Feature/주문목록 #120
  src/components/common/InputAddressWithMap.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/ContactModal.tsx
  src/components/features/MyPage/Info/Delivery.tsx
  src/components/features/MyPage/Info/Logout.tsx
  src/components/features/MyPage/Info/MyInfo.tsx
  src/components/features/MyPage/Info/Withdraw.tsx
  src/components/features/MyPage/Order/ContactModal.tsx
  src/components/features/MyPage/Order/OrderProcessModal.tsx
  src/components/features/MyPage/OrderItem/ProductOrderItem.tsx
  src/components/features/MyPage/OrderItem/index.tsx
  src/components/features/MyPage/OrderProcessModal.tsx
  src/components/features/SellerPage/SellerCategory.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/MyPageLayout.tsx
  src/mocks/mockItem/mockOrder.ts
  src/pages/MyPage/DeliveryPage.tsx
  src/pages/MyPage/MyInfoPage.tsx
  src/pages/MyPage/OrdersPage.tsx
  src/pages/MyPage/WithdrawPage.tsx
  src/pages/MyPage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
Labels: 💎 기능 개발, 🎨 디자인

#134 Feature/review #133
  src/components/features/MyPage/Order/ReviewModal.tsx
  src/components/features/MyPage/OrderItem/ProductOrderItem.tsx
Labels: 💎 기능 개발

#136 Feature/mypage #135
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/Order/FarmList.tsx
  src/components/features/MyPage/Order/ReviewList.tsx
  src/components/features/MyPage/Order/WriteReviewComponent.tsx
  src/pages/MyPage/FarmListPage.tsx
  src/pages/MyPage/ReviewListPage.tsx
  src/routes/AppRouter.tsx
Labels: 🔨 리팩토링

#137 Feature/판매자목록 #132
  src/components/features/ProductCartPage/CartItem.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/AddProduct/index.tsx
  src/components/features/SellerPage/BusinessRegister/index.tsx
  src/components/features/SellerPage/MyInfo/EditInfo.tsx
  src/components/features/SellerPage/MyInfo/Logout.tsx
  src/components/features/SellerPage/SellerCategory.tsx
  src/components/features/SellerPage/Tax.tsx/index.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/layouts/SellerLayout.tsx
  src/mocks/mockItem/mockProducts.ts
  src/pages/ProductCartPage/index.tsx
  src/pages/SellerPage/BizRegister.tsx
  src/pages/SellerPage/FarmEdit.tsx
  src/pages/SellerPage/FarmRegister.tsx
  src/pages/SellerPage/ProductEdit.tsx
  src/pages/SellerPage/ProductRegister.tsx
  src/pages/SellerPage/RecentOrders.tsx
  src/pages/SellerPage/SellerMyInfo.tsx
  src/pages/SellerPage/SellerProductList.tsx
  src/pages/SellerPage/SellerWithdraw.tsx
  src/pages/SellerPage/SoldOuts.tsx
  src/pages/SellerPage/TaxCalculator.tsx
  src/pages/SellerPage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
Labels: 💎 기능 개발, 🎨 디자인

#141 Feature/header refactoring #140
  src/api/axiosInstance.ts
  src/api/intercepters.ts
  src/atoms/userAtom.ts
  src/components/common/KaKaoLoginButton.tsx
  src/components/layouts/Header.tsx
  src/hooks/useLogin.ts
Labels: 🔨 리팩토링

#142 Feature/order refactor #139
  src/api/businessApi.ts
  src/api/farmApi.ts
  src/api/productApi.ts
  src/api/reviewApi.ts
  src/api/wishlistApi.ts
  src/components/features/FarmDetailPage/Product.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/Order/ContactModal.tsx
  src/components/features/MyPage/Order/FarmList.tsx
  src/components/features/MyPage/Order/ReviewList.tsx
  src/components/features/MyPage/Order/ReviewModal.tsx
  src/components/features/MyPage/OrderItem/ProductOrderItem.tsx
  src/components/features/MyPage/Wishlist/ProductWish.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/AddProduct/index.tsx
  src/components/features/SellerPage/AddProduct/type.ts
  src/components/features/SellerPage/BusinessRegister/index.tsx
  src/components/features/SellerPage/Tax.tsx/index.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/layouts/Header.tsx
  src/mocks/mockItem/mockReviews.ts
  src/pages/MyPage/FarmListPage.tsx
  src/pages/MyPage/ProductWishlistPage.tsx
  src/pages/MyPage/ReviewListPage.tsx
  src/pages/StoreDetailPage/index.tsx
  src/pages/WishPage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
Labels: 🔨 리팩토링

#149 Feature/order refactor #139
  src/api/emailApi.ts
  src/api/productApi.ts
  src/components/features/MyPage/Category.tsx
  src/components/features/StorePage/StoreBanner.tsx
  src/pages/MyPage/ProductWishlistPage.tsx
Labels: 🔨 리팩토링

#150 refactor: farm list 수정
  src/components/features/MyPage/Order/FarmList.tsx
  src/mocks/mockItem/mockFarms.ts
  src/pages/MyPage/FarmListPage.tsx
  src/types/index.ts
Labels: 🔨 리팩토링

#148 Feature/카드 리펙토링 #145
  src/components/common/KaKaoLoginButton.tsx
  src/components/features/SchedulePage/ScheduleCard.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/features/StorePage/ProductList/ProductFilter/index.tsx
  src/components/features/StorePage/ProductList/index.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/ScrollSaver.tsx
  src/hooks/useLogin.ts
  src/hooks/useScrollSaver.ts
  src/pages/CallbackPage/index.tsx
  src/pages/Home/index.tsx
  src/pages/ProductDetailPage/index.tsx
  src/routes/AppRouter.tsx
Labels: 🔨 리팩토링

#153 Feature/footer 리펙토링 #146
  src/api/axiosInstance.ts
  src/api/businessApi.ts
  src/api/emailApi.ts
  src/api/farmApi.ts
  src/api/intercepters.ts
  src/api/productApi.ts
  src/api/reviewApi.ts
  src/api/storeApi.ts
  src/api/wishlistApi.ts
  src/atoms/userAtom.ts
  src/components/common/KaKaoLoginButton.tsx
  src/components/features/FarmDetailPage/ProductDescription.tsx
  src/components/features/FarmDetailPage/Schedule.tsx
  src/components/features/IntroductionPage/Introduction.tsx
  src/components/features/MyPage/Category.tsx
  src/components/features/MyPage/Order/ContactModal.tsx
  src/components/features/MyPage/Order/FarmList.tsx
  src/components/features/MyPage/Order/ReviewList.tsx
  src/components/features/MyPage/Order/ReviewModal.tsx
  src/components/features/MyPage/OrderItem/ProductOrderItem.tsx
  src/components/features/MyPage/Wishlist/ProductWish.tsx
  src/components/features/SchedulePage/ScheduleCard.tsx
  src/components/features/SellerPage/AddFarm/index.tsx
  src/components/features/SellerPage/AddProduct/index.tsx
  src/components/features/SellerPage/AddProduct/type.ts
  src/components/features/SellerPage/BusinessRegister/index.tsx
  src/components/features/SellerPage/MyInfo/Logout.tsx
  src/components/features/SellerPage/Tax.tsx/index.tsx
  src/components/features/StoreDetailPage/Product.tsx
  src/components/features/StoreDetailPage/ProductDescription.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/features/StorePage/ProductList/ProductFilter/index.tsx
  src/components/features/StorePage/ProductList/index.tsx
  src/components/features/StorePage/StoreBanner.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/MyPageLayout.tsx
  src/components/layouts/ScrollSaver.tsx
  src/hooks/useLogin.ts
  src/hooks/useScrollSaver.ts
  src/mocks/mockItem/mockFarms.ts
  src/mocks/mockItem/mockReviews.ts
  src/pages/CallbackPage/index.tsx
  src/pages/FarmDetailPage/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyPage/FarmListPage.tsx
  src/pages/MyPage/OrdersPage.tsx
  src/pages/MyPage/ProductWishlistPage.tsx
  src/pages/MyPage/ReviewListPage.tsx
  src/pages/ProductDetailPage/index.tsx
  src/pages/WishPage/index.tsx
  src/routes/AppRouter.tsx
  src/types/index.ts
Labels: 🔨 리팩토링

#156 Feature/이미지api #147
  src/api/farmApi.ts
  src/api/imageApi.ts
  src/api/productApi.ts
  src/components/features/MyPage/Order/CancelOrderModal.tsx
  src/components/features/MyPage/Order/RefundModal.tsx
  src/components/features/MyPage/Order/useGetProduct.tsx
  src/components/features/RegisterPage/Farmer.tsx
  src/components/features/SchedulePage/BestScheduleSection.tsx
  src/components/features/SchedulePage/ScheduleCard.tsx
  src/components/features/StorePage/ProductCard.tsx
  src/components/features/StorePage/ProductList/ProductFilter/index.tsx
  src/components/features/StorePage/ProductList/ProductsView.tsx
  src/components/features/StorePage/ProductList/index.tsx
  src/mocks/mockItem/mockSchedule.ts
  src/pages/SchedulePage/index.tsx
  src/pages/SellerPage/SellerProductList.tsx
  src/types/index.ts
Labels: 💎 기능 개발, 🔨 리팩토링
